### ISSUE TITLE
Remove use of deprecated stop=False

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_MLX90393#18]
Remove use of `stop=False`.   This option is not supported in CircuitPython 6.x. https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/blob/master/adafruit_mlx90393.py#L165

It looks like this will affect the setter of "gain", since it sends a payload of more than 1 byte.  This property is unconditionally set in the constructor, so it may be the case that this driver cannot be used with 6.x until this is addressed.

**Comment by jepler** [comment]
See https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/pull/54

**Comment by ladyada** [comment]
@caternuson is this also resolved?

**Comment by caternuson** [comment]
Hmmm...maybe that's what lint was griping about. So, no. Not resolved. Forgot about this change. I'll PR this right quick....

**Comment by caternuson** [comment]
Fixed with #23
