### ISSUE TITLE
AttributeError: 'MLX90393' object has no attribute 'magnetic'

### ISSUE THREAD

**Issue by andrasfuchs** [adafruit/Adafruit_CircuitPython_MLX90393#7]
I'm a total newbie, so forgive me if it has an obvious solution :) 

I followed the tutorial here:
https://learn.adafruit.com/mlx90393-wide-range-3-axis-magnetometer/circuitpython

I installed the Adafruit CircuitPython MLX90393 with the following command:
`sudo pip3 install adafruit-circuitpython-mlx90939`

Then I copied the [adafruit_mlx90393_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/blob/master/examples/adafruit_mlx90393_simpletest.py) file to the Raspberry and run this:
`sudo python3 ~/Documents/Work/adafruit_mlx90393_simpletest.py`

And got this:

```
Traceback (most recent call last):
  File "/home/pi/Documents/Work/adafruit_mlx90393_simpletest.py", line 11, in <module>
    MX, MY, MZ = SENSOR.magnetic
AttributeError: 'MLX90393' object has no attribute 'magnetic'
```

**Comment by ladyada** [comment]
hmm i wonder if it didn't get bumped - @kattni check if pypi is the latest
https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/releases
?

**Comment by kattni** [comment]
Travis indicated the deployment was successful. Checking PyPI shows it has the latest: https://pypi.org/project/adafruit-circuitpython-mlx90393/

**Comment by andrasfuchs** [comment]
I run the `sudo pip3 install adafruit-circuitpython-mlx90939` command again on the Pi and got this:
```
Requirement already satisfied: adafruit-circuitpython-mlx90939 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: Adafruit-Blinka in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-mlx90939)
Requirement already satisfied: adafruit-circuitpython-busdevice in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-mlx90939)
Requirement already satisfied: Adafruit-PlatformDetect in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
Requirement already satisfied: sysv-ipc in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
Requirement already satisfied: Adafruit-PureIO in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
Requirement already satisfied: rpi-ws281x>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-mlx90939)
```

But when I browsed to the _/usr/local/lib/python3.5/dist-packages_ folder, it seems like I don't have the current 1.2 version:
![image](https://user-images.githubusercontent.com/910321/54908473-447e0700-4ee8-11e9-804d-5b6ac319a6ef.png)

**Comment by andrasfuchs** [comment]
Sorry, it was my mistake!

I installed the adafruit-circuitpython-mlx90939 and not the adafruit-circuitpython-**mlx90393**!

It works now!

**Comment by kattni** [comment]
@andrasfuchs I've managed to typo the same thing before! Glad you got it working!
