### ISSUE TITLE
OSError: [Errno 121] Remote I/O error on second run

### ISSUE THREAD

**Issue by andrasfuchs** [adafruit/Adafruit_CircuitPython_MLX90393#8]
When I run the [adafruit_mlx90393_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/blob/master/examples/adafruit_mlx90393_simpletest.py) script for the first time, it runs correctly.

![image](https://user-images.githubusercontent.com/910321/55076853-b7c57b80-5096-11e9-8c89-c3b990e02bba.png)
[note: I made some formatting changes, but I didn't touch the sensor communication instructions]

But when I run the exact same script again, I get "OSError: [Errno 121] Remote I/O error":
![image](https://user-images.githubusercontent.com/910321/55076899-d461b380-5096-11e9-88a5-471743319114.png)

I tried to disable and re-enable the I2C bus on my Raspberry Pi 3 Model B, but the only thing that fixed it was restarting the Pi, so I need to restart it every single time I want to test the sensor.

**Comment by caternuson** [comment]
How are you stopping the first run of the program? <CTRL><C>?

After stopping the first run, try power cycling the MLX before the second run. You can just pull the VIN wire out for a bit and put it back in.

**Comment by ladyada** [comment]
MLX has a terrible i2c interface, the chip may require a power cycle if you stop it mid-conversion?

**Comment by andrasfuchs** [comment]
I tried the power cycle, but it didn't fix the problem.

I also made the infinite loop finite with a counter, so that I don't need to manually terminate the script with Ctrl+C, but the results were the same as before.

Then I commented some lines of the script to check if the bus initialization or the value reading causes the problem.

The only thing that fixed it when I commented the `MX, MY, MZ = SENSOR.magnetic` line.

**Comment by ladyada** [comment]
well, thats the line that reads the sensor ;) is there any other MLX library that works? we could see if they do something different
i wonder if we call reset() earlier if that will help https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/blob/master/adafruit_mlx90393.py#L141

andra, can you try downloading the 'raw' python file and uninstalling from pip so you can make adjustments to the library to try different things?

**Comment by andrasfuchs** [comment]
@ladyada Sure, I'd be glad to help in any way. Could you tell me how should I do that? That's my first python project to be honest :) I think I know how to uninstall the library with pip, but could you assist me with the "raw python file" usage?

I also have an [Adafruit ADS1115](https://www.adafruit.com/product/1085) and a [ATSAMD09 seesaw](https://www.adafruit.com/product/3657), I'm not sure if they can assist the testing in any way.

**Comment by ladyada** [comment]
@kattni @caternuson do either of you have an MLX sensor you can also try with?

**Comment by caternuson** [comment]
@ladyada Sorry, I do not :(

**Comment by kattni** [comment]
@ladyada It looks like I do have one. I need to get it assembled, and then try it on Pi.

**Comment by kattni** [comment]
@ladyada It looks like I do have one. I need to get it assembled, and then try it on Pi.

**Comment by haikunguyen** [comment]
@ladyada  I found this piece of code online for a different MLX90393.  It runs every time without fail even after a ctrl+C interrupt.  I noticed that if I run this code first, then run your guys' simpletest code, it would run fine.

Other code:

# Distributed with a free-will license.
# Use it any way you want, profit or free, provided it fits in the licenses of its associated works.
# MLX90393
# This code is designed to work with the MLX90393_I2CS I2C Mini Module available from ControlEverything.com.
# https://www.controleverything.com/products
import smbus
import time
# Get I2C bus
bus = smbus.SMBus(1)
# MLX90393 address, 0x0C(12)
# Select write register command, 0x60(96)
# AH = 0x00, AL = 0x5C, GAIN_SEL = 5, Address register (0x00 << 2)
config = [0x00, 0x5C, 0x00]
bus.write_i2c_block_data(0x0C, 0x60, config)
# Read data back, 1 byte
# Status byte
data = bus.read_byte(0x0C)
# MLX90393 address, 0x0C(12)
# Select write register command, 0x60(96)
# AH = 0x02, AL = 0xB4, RES for magnetic measurement = 0, Address register (0x02 << 2)
config = [0x02, 0xB4, 0x08]
bus.write_i2c_block_data(0x0C, 0x60, config)
# Read data back, 1 byte
# Status byte
data = bus.read_byte(0x0C)
# MLX90393 address, 0x0C(12)

while(True):
# Start single meaurement mode, X, Y, Z-Axis enabled
        bus.write_byte(0x0C, 0x3E)
# Read data back, 1 byte
# Status byte
        data = bus.read_byte(0x0C)
        time.sleep(0.5)
# MLX90393 address, 0x0C(12)

# Read data back from 0x4E(78), 7 bytes
# Status, xMag msb, xMag lsb, yMag msb, yMag lsb, zMag msb, zMag lsb
        data = bus.read_i2c_block_data(0x0C, 0x4E, 7)

# Convert the data
        xMag = data[1] * 256 + data[2]
        if xMag > 32767 :
            xMag -= 65536
        yMag = data[3] * 256 + data[4]
        if yMag > 32767 :
                yMag -= 65536
        zMag = data[5] * 256 + data[6]
        if zMag > 32767 :
                zMag -= 65536

# Output data to screen
        print ("Magnetic Field in X-Axis : %d" %xMag)
        print ("Magnetic Field in Y-Axis : %d" %yMag)
        print ("Magnetic Field in Z-Axis : %d" %zMag)

**Comment by caternuson** [comment]
This sensor appears to want repeated starts.
![image](https://user-images.githubusercontent.com/8755041/59648829-42b58f80-9135-11e9-9714-d5a27b70b0ca.png)
which requires special attention on Linux SBC's:
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/master/adafruit_bus_device/i2c_device.py#L147
The above is limited to a single byte for the write:
https://github.com/adafruit/Adafruit_Blinka/blob/master/src/adafruit_blinka/microcontroller/generic_linux/i2c.py#L62
There are two commands that send out more than one byte on the write:
![image](https://user-images.githubusercontent.com/8755041/59648967-b0fa5200-9135-11e9-8c6f-9eb0e3fb2fdf.png)

The sensor appears to be somewhat forgiving about the repeated starts since it was working for the most part without them in the current driver. But by aborting the read loop and starting over the sensor was in a bad state and wouldn't play nice. A power cycle does fix this, but you have to pull all the wires - it stays back powered through the logic pins.

Not sure why same thing does not happen on a native CP board (M4, etc).

Anywho, checkout PR #10 for a possible fix.

**Comment by siddacious** [comment]
excellent find and analysis @caternuson!

**Comment by ladyada** [comment]
merged!

**Comment by caternuson** [comment]
@andrasfuchs Please try the 1.3.0 release when it becomes available:
https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/releases/tag/1.3.0

**Comment by andrasfuchs** [comment]
Thank you guys for your efforts! I can confirm that it works perfectly now.
